---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-logging
  annotations:
    openshift.io/description: "This project contains the Openshift Logging resources"
    openshift.io/display-name: "Openshift Logging"
