---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: sealed-secrets
  annotations:
    openshift.io/description: "This project contains the Sealed Secrets project"
    openshift.io/display-name: "RHTE - Sealed Secrets"